name: $(majorMinorVersion).$(semanticVersion) # $(rev:r) # NOTE: rev resets when the default retention period expires

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
pr: none

pool: HAWKEYE

variables:
  majorMinorVersion: 0.2
  # semanticVersion counter is automatically incremented by one in each execution of pipeline
  # second parameter is seed value to reset to every time the referenced majorMinorVersion is changed
  semanticVersion: $[counter(variables['majorMinorVersion'], 1)]
  solution: '**/Ekom.Payments.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:

- task: UseDotNet@2
  displayName: Use DotNet $(dotNetVersion)
  inputs:
    packageType: 'sdk'
    version: '$(dotNetVersion)'
    performMultiLevelLookup: true
    
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    projects: '*.sln'
    feedsToUse: 'select'
    vstsFeed: '2ec80bf7-377e-42e0-9fcd-fe6b6fd9660f'


- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Ekom.Payments.Core.csproj;**/Ekom.Payments.AspNetCore.csproj;**/Ekom.Payments.U10.csproj;**/Ekom.Payments.Valitor.csproj;**/Ekom.Payments.Borgun.csproj;**/Ekom.Payments.Netgiro.csproj;**/Ekom.Payments.Straumur.csproj;'
    includesymbols: true
    versioningScheme: 'byBuildNumber'


- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.snupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'VV Public NuGet'

- task: PublishSymbols@2
  inputs:
    SearchPattern: '**/bin/**/*.pdb'
    SymbolServerType: 'TeamServices'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'