<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>Ekom.Payments.U18</AssemblyName>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <RootNamespace>Ekom.Payments.Umb</RootNamespace>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- Package properties -->
        <PackageId>Ekom.Payments.U18</PackageId>
        <Version>0.0.1</Version>
        <Title>Ekom Payments Umbraco 18</Title>
        <Authors>Vettvangur</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/Vettvangur/Ekom.Payments</PackageProjectUrl>
        <PackageIcon>images\VV_Logo.png</PackageIcon>
        <Description>Ekom Payments - Umbraco E-Commerce solution</Description>
        <PackageReleaseNotes>Initial Umbraco 18 support</PackageReleaseNotes>
        <Copyright>Copyright 2026</Copyright>
        <PackageTags>Ekom Umbraco Payments</PackageTags>

        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>
    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\VV_Logo.png" Pack="true" PackagePath="images\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
        <PackageReference Include="Umbraco.Cms.Core" Version="18.0.0" />
        <PackageReference Include="Umbraco.Cms.Web.Common" Version="18.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\AspNetCore\Ekom.Payments.AspNetCore.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\Ekom.Payments.Umbraco.Shared\EkomStartup.cs" Link="EkomStartup.cs" />
        <Compile Include="..\Ekom.Payments.Umbraco.Shared\ApplicationBuilderExtensions.cs" Link="ApplicationBuilderExtensions.cs" />
        <Compile Include="..\Ekom.Payments.Umbraco.Shared\OptionalPaymentProviderRegistration.cs" Link="OptionalPaymentProviderRegistration.cs" />
        <Compile Include="..\Ekom.Payments.Umbraco.Shared\Services\UmbracoPaymentExecutionContext.cs" Link="Services\UmbracoPaymentExecutionContext.cs" />
        <Compile Include="..\Ekom.Payments.Umbraco.Shared\Services\UmbracoService.cs" Link="Services\UmbracoService.cs" />
    </ItemGroup>
</Project>
